// Package gitclone provides reusable git clone management with lifecycle control,
// concurrency management, and large repository optimizations.
package gitclone

import (
	"bufio"
	"context"
	"os"
	"os/exec"
	"strings"
	"sync"
	"time"

	"github.com/alecthomas/errors"

	"github.com/block/cachew/internal/logging"
)

// credentialFileRefreshInterval controls how often the background goroutine
// re-fetches the GitHub App token and rewrites the on-disk credential file.
// GitHub App installation tokens are valid for 1 hour and the TokenManager's
// own cache refreshes ~5 minutes before expiry, so 30 s is dense enough to
// pick up rotations within a window that git lfs will tolerate (it retries
// failed batch requests several times with exponential backoff).
const credentialFileRefreshInterval = 30 * time.Second

// GitCommand returns a git subprocess configured with repository-scoped
// authentication and any per-URL git config overrides disabled.
//
// When a GitHub App credential provider is configured and the upstream is a
// github.com URL, the token is written to a 0600 temporary file and exposed
// to git via a credential.helper that reads the file on every invocation. A
// background goroutine then refreshes the token in-place for the lifetime of
// the returned cleanup, so long-running subprocesses (notably `git lfs fetch`
// against large repos like ios-register / cash-ios) survive the 1-hour token
// TTL instead of failing with "Bad credentials" once the embedded token
// expires mid-fetch.
//
// Callers MUST invoke the returned cleanup (typically via defer) once the
// command has finished, to stop the refresh goroutine and remove the token
// file from disk. cleanup is always non-nil and is safe to call multiple
// times, including when GitCommand returns an error.
func (r *Repository) GitCommand(ctx context.Context, args ...string) (*exec.Cmd, func(), error) {
	cleanup := func() {}

	configArgs, err := getInsteadOfDisableArgsForURL(ctx, r.upstreamURL)
	if err != nil {
		return nil, cleanup, errors.Wrap(err, "get insteadOf disable args")
	}

	var allArgs []string
	allArgs = append(allArgs, configArgs...)

	if r.credentialProvider != nil && strings.Contains(r.upstreamURL, "github.com") {
		token, err := r.credentialProvider.GetTokenForURL(ctx, r.upstreamURL)
		if err == nil && token != "" {
			credFile, fileCleanup, err := r.startTokenCredentialFile(ctx, token)
			if err != nil {
				return nil, cleanup, errors.Wrap(err, "start token credential file")
			}
			cleanup = fileCleanup
			// `!<cmd>` tells git to run <cmd> via the shell on every credential
			// query. `cat` re-reads the file each time, so a rewrite by the
			// refresh goroutine is picked up automatically by git-lfs retries
			// after a token rotation.
			allArgs = append(allArgs, "-c", "credential.helper=!cat "+shellSingleQuote(credFile))
		}
	}

	allArgs = append(allArgs, args...)

	return exec.CommandContext(ctx, "git", allArgs...), cleanup, nil
}

// startTokenCredentialFile creates a 0600 temp file containing a git
// credential helper response for the given initial token, and spawns a
// background goroutine that re-fetches the token and rewrites the file as
// long as the returned cleanup has not been called and ctx has not been
// cancelled. The credential file path is returned so callers can wire it
// into git's credential.helper config.
func (r *Repository) startTokenCredentialFile(ctx context.Context, initialToken string) (string, func(), error) {
	f, err := os.CreateTemp("", "cachew-git-cred-*")
	if err != nil {
		return "", func() {}, errors.Wrap(err, "create credential file")
	}
	// path is generated by os.CreateTemp under os.TempDir(); the file
	// descriptor is owned by this process and never user-controlled.
	path := f.Name()
	if err := f.Close(); err != nil {
		_ = os.Remove(path) //nolint:gosec // path is from os.CreateTemp
		return "", func() {}, errors.Wrap(err, "close credential file")
	}
	if err := os.Chmod(path, 0o600); err != nil { //nolint:gosec // path is from os.CreateTemp
		_ = os.Remove(path) //nolint:gosec // path is from os.CreateTemp
		return "", func() {}, errors.Wrap(err, "chmod credential file")
	}
	if err := writeCredentialFile(path, initialToken); err != nil {
		_ = os.Remove(path) //nolint:gosec // path is from os.CreateTemp
		return "", func() {}, err
	}

	refreshCtx, cancel := context.WithCancel(ctx)
	var once sync.Once
	cleanup := func() {
		once.Do(func() {
			cancel()
			_ = os.Remove(path) //nolint:gosec // path is from os.CreateTemp
		})
	}

	go r.refreshCredentialFile(refreshCtx, path, initialToken)

	return path, cleanup, nil
}

// refreshCredentialFile is the body of the token-refresh goroutine started by
// startTokenCredentialFile. It calls refreshCredentialFileOnce on a ticker
// and rewrites the credential file whenever the token changes. The
// TokenManager caches tokens internally so most ticks are a cheap map
// lookup; only the pre-expiry refresh actually hits the GitHub API.
func (r *Repository) refreshCredentialFile(ctx context.Context, path, current string) {
	logger := logging.FromContext(ctx).With("upstream", r.upstreamURL, "cred_file", path)
	ticker := time.NewTicker(credentialFileRefreshInterval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			next, changed, err := r.refreshCredentialFileOnce(ctx, path, current)
			switch {
			case err != nil:
				logger.WarnContext(ctx, "Failed to refresh git credential file", "error", err)
			case changed:
				logger.DebugContext(ctx, "Git credential file refreshed with rotated token")
				current = next
			}
		}
	}
}

// refreshCredentialFileOnce performs a single tick of the refresh loop: it
// fetches the current token from the credential provider and, when the value
// differs from current, atomically rewrites path. It returns the latest token
// it observed, whether path was actually rewritten, and any error.
func (r *Repository) refreshCredentialFileOnce(ctx context.Context, path, current string) (string, bool, error) {
	token, err := r.credentialProvider.GetTokenForURL(ctx, r.upstreamURL)
	if err != nil {
		return current, false, errors.Wrap(err, "fetch token")
	}
	if token == "" || token == current {
		return current, false, nil
	}
	if err := writeCredentialFile(path, token); err != nil {
		return current, false, err
	}
	return token, true, nil
}

// writeCredentialFile atomically writes the git credential helper response
// for the given token to path. The on-disk format mirrors what git expects
// to read from a `get` query on stdout, so `credential.helper=!cat <path>`
// satisfies the protocol without any shell-level templating of the token.
func writeCredentialFile(path, token string) error {
	body := "username=x-access-token\npassword=" + token + "\n"
	tmp := path + ".new"
	if err := os.WriteFile(tmp, []byte(body), 0o600); err != nil { //nolint:gosec // path derives from os.CreateTemp
		return errors.Wrap(err, "write temp credential file")
	}
	if err := os.Rename(tmp, path); err != nil { //nolint:gosec // path derives from os.CreateTemp
		_ = os.Remove(tmp) //nolint:gosec // path derives from os.CreateTemp
		return errors.Wrap(err, "rename credential file")
	}
	return nil
}

// shellSingleQuote returns s safely wrapped in POSIX single quotes for
// inclusion in a `sh -c` command line. Embedded single quotes are escaped
// by closing the quoted segment, inserting an escaped quote, and reopening.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func getInsteadOfDisableArgsForURL(ctx context.Context, targetURL string) ([]string, error) {
	if targetURL == "" {
		return nil, nil
	}

	cmd := exec.CommandContext(ctx, "git", "config", "--get-regexp", "^url\\..*\\.(insteadof|pushinsteadof)$")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return []string{}, nil //nolint:nilerr
	}

	var args []string
	scanner := bufio.NewScanner(strings.NewReader(string(output)))
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.Fields(line)
		if len(parts) >= 2 {
			configKey := parts[0]
			pattern := parts[1]

			if strings.HasPrefix(targetURL, pattern) {
				args = append(args, "-c", configKey+"=")
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, errors.Wrap(err, "scan insteadOf output")
	}

	return args, nil
}

func ParseGitRefs(output []byte) map[string]string {
	refs := make(map[string]string)
	scanner := bufio.NewScanner(strings.NewReader(string(output)))
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.Fields(line)
		if len(parts) >= 2 {
			sha := parts[0]
			ref := parts[1]
			refs[ref] = sha
		}
	}
	return refs
}
